#!/bin/bash
#
# server - run the service
#

set -e

cd "$(dirname "$0")/.."

export CONTEXT="all"
UPDATE=${UPDATE:-false}

if [ "$UPDATE" = "true" ]; then
  script/update
fi

# Check for Swarm mode.
SWARM=$(docker info 2>/dev/null | grep '^ Swarm' | awk '{ print $NF }')

if [ "$SWARM" = "inactive" ] ; then
  COMPOSE_FILES="-f docker-compose.yml -f docker-compose-database.yml"
  echo "==> Running in compose mode (Swarm mode is ${SWARM})."
  if [ "$1" = "--stop" ]; then
    echo "==> Stopping the service..."
    docker-compose $COMPOSE_FILES down
  else
    echo "==> Starting the service..."
    export CONFIG_FORCE_SSL=${CONFIG_FORCE_SSL:-false}
    docker-compose $COMPOSE_FILES up -d
  fi
else
  echo "==> Running in Swarm mode..."
  source ../env.swarm
  STACK=$(echo $SERVER_NAME | sed -e 's/\./_/g')
  if [ "$1" = "--stop" ]; then
    echo "==> Stopping the service..."
    docker stack rm ${STACK}
  else
    echo "==> Deploying the stack..."
    docker stack deploy -c docker-compose.yml ${STACK}
  fi
fi
