#!/bin/bash
#
# server - run the service
#

set -e

cd "$(dirname "$0")/.."

export CONTEXT="all"
UPDATE=${UPDATE:-false}

if [ "$UPDATE" = "true" ]; then
  script/update
fi

# Check for Swarm mode.
SWARM=$(docker info 2>/dev/null | grep ^Swarm | awk '{ print $NF }')

if [ "$SWARM" = "inactive" ] ; then
  echo "==> Running in compose mode (Swarm mode is ${SWARM})."
  if [ "$1" = "--stop" ]; then
    echo "==> Stopping the service..."
    docker-compose down
  else
    echo "==> Starting the service..."
    export CONFIG_FORCE_SSL=${CONFIG_FORCE_SSL:-false}
    docker-compose up -d
  fi
else
  echo "==> Swarm support TBC."
fi
