#!/bin/bash
#
# setup - clean slate for the project
#

set -e

cd "$(dirname "$0")/.."

# Check to see if we've got a specific context.
export CONTEXT=${CONTEXT:-all}

# run bootstrap
script/bootstrap

# Check for Swarm mode.
SWARM=$(docker info 2>/dev/null | grep '^ Swarm' | awk '{ print $NF }')

echo "==> Cleaning up submodules..."
git submodule foreach git reset --hard
git submodule foreach git clean -f

if [ "$CONTEXT" != "build" ]; then

  echo "==> Setting up for deployment."

  if  [ "$SWARM" = "inactive" ] ; then
    COMPOSE_FILES="-f docker-compose.yml -f docker-compose-database.yml"
    echo "==> Running in compose mode (Swarm mode is ${SWARM})."

    echo "==> Removing the stack and any associated volumes..."
    docker-compose $COMPOSE_FILES down -v

    echo "==> Initialising the database..."
    docker-compose $COMPOSE_FILES up -d database
    sleep 5
    docker-compose $COMPOSE_FILES run --rm app rake db:schema:load
    docker-compose $COMPOSE_FILES run --rm app rake db:migrate
    docker-compose $COMPOSE_FILES run --rm app rake db:seed

    if [ "$SEED_DB" = "true" ]; then
      echo "==> Loading test data into database..."
      docker-compose $COMPOSE_FILES run --rm -e RAILS_GROUPS=test -e DATABASE_CLEANER_ALLOW_PRODUCTION=true -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true app rake db:dev_seed
    else
      echo "==> Not loading seed data into the database. If you want to do this, re-run with SEED_DB=true."
    fi

    docker-compose $COMPOSE_FILES down

  else
    echo "==> Running in Swarm mode."
    source ../env.swarm
    STACK=$(echo $SERVER_NAME | sed -e 's/\./_/g')
    echo "==> Removing stack ${STACK}..."
    docker stack rm $STACK
    sleep 5
    if docker volume inspect ${STACK}_consul-system >/dev/null 2>&1 ; then
      echo "==> Removing system volume..."
      docker volume rm ${STACK}_consul-system
    fi
    echo "==> Initialising the database..."
    docker-compose -p ${STACK} run --rm app rake db:schema:load
    docker-compose -p ${STACK} run --rm app rake db:seed
    docker-compose down -v
  fi

fi

echo "==> Setup completed."
